openapi: 3.1.0
info:
  version: 1.0.0
  title: Tasteorama
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is an app for saving and adding recipes.

tags:
  - name: Auth
    description: Registration and authentication
  - name: Users
    description: User information
  - name: Categories
    description: Recipe Categories
  - name: Ingridients
    description: Ingridients
  - name: Recipes
    description: Recipes operation

paths:
  /recipes/{recipeId}:
    get:
      $ref: '../swagger/paths/recipe/{recipeId}/get.yaml'

servers:
  - url: http://localhost:5000
  - url: https://group2-b.onrender.com

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
