openapi: 3.1.0
info:
  version: 1.0.0
  title: Tasteorama
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is an app for saving and adding recipes.

tags:
  - name: Auth
    description: Registration and authentication
  - name: Users
    description: User information
  - name: Categories
    description: Recipe Categories
  - name: Ingridients
    description: Ingridients
  - name: Recipes
    description: Recipes operation

servers:
  - url: https://group2-b.onrender.com

paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/users/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/users/auth/login.yaml'
  /user/refresh:
    post:
      $ref: '../swagger/paths/users/auth/refresh.yaml'
  /user/logout:
    post:
      $ref: '../swagger/paths/users/auth/logout.yaml'

  /users/current:
    get:
      $ref: '../swagger/paths/users/current/get.yaml'
  /categories:
    get:
      $ref: '../swagger/paths/categories.yaml'
  /ingredients:
    get:
      $ref: '../swagger/paths/ingredients.yaml'
  /recipes:
    get:
      $ref: '../swagger/paths/recipe/get_search.yaml'

  /recipes/{recipeId}:
    get:
      $ref: '../swagger/paths/recipe/{recipeId}/get.yaml'
    post:
      $ref: '../swagger/paths/recipe/{recipeId}/add_favorite.yaml'
    delete:
      $ref: '../swagger/paths/recipe/{recipeId}/delete_favorite.yaml'

  /recipes/my:
    get:
      $ref: '../swagger/paths/recipe/get_own.yaml'
  /recipes/add:
    post:
      $ref: '../swagger/paths/recipe/post_resipe.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
